### ISSUE TITLE
Outlook

### ISSUE THREAD

**Issue by section1** [section1/section1#1]
Hi @mdrobisch i invoke you to ask something, i view your replies about nextcloud events .. and i want to know what do you use to check free/busy availability in Outlook ? and what outlook do you use.. because we use outlook that come with 36 and and i can't find hot to check the free/busy slot of a person in nextcloud. thanks.

**Comment by mdrobisch** [comment]
Hi @section1 , actually we did not got the FreeBusy feature working either. Actually we tried to solve this by using CalDavSync https://caldavsynchronizer.org but while the starting was promising problems keeped popping up. Actually we suggest our users to use the web interface of nextcloud for this or going with e.g. Thunderbird.

Hopefully my answer helps you.

**Comment by section1** [comment]
Hi @mdrobisch, thanks for the reply, yeah we are in the same situation here...
